project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - projections.qmd
  resources:
    - data/
    - favicon.ico

website:
  title: "Transfer Portal Projections"
  site-url: "https://glederer04.github.io/Test-Transfer-Portal-Model/"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Projections1
        file: projections.qmd
  favicon: favicon.ico

format:
  html:
    theme: cosmo
    toc: false